import LocalizedStrings from 'react-native-localization';



export let strings = new LocalizedStrings({
    "fr-US":{
        parametre:"Paramétres",
        votre_ref:"Votre référence",
        votre_profil:"Profile",
        chnage_ref:"Changer la référence",
        add_ref:"Pour continuer ajouter une référence",
        factur:"Facturation",
        hist:"Historique",
        demande:"Demande",
        rec:"Réclamation",
        bt_env:"Envoyer",
        datedeb:"Date de Debut",
        period_cons:"Période de Consommation:",
        usage:"Usage",
        moisWehed:"1 mois",
        moisWehed2:"2 mois",
        moisWehed4:"4 mois",
        moisWehed6:"6 mois",
        moisWehed8:"8 mois",
        moisWehed10:"10 mois",
        moisWehed12:"12 mois",
        fils:"2 fils - 5 A",
        fils1:"2 fils - 10 A",
        fils2:"2 fils - 5 A",
        fils3:"2 fils - 15 A",
        fils4:"2 fils - 20 A",
        fils5:"2 fils - 30 A",
        fils6:"2 fils - 45 A",
        fils7:"2 fils - 63 A",
        fils8:"2 fils - 100 A",
        fils9:"2 fils - 125 A",
        fils10:"2 fils - 160 A",
        fils11:"2 fils - 225 A",
        fils12:"4 fils - 5 A",
        fils13:"4 fils - 10 A",
        fils14:"4 fils - 15 A",
        fils15:"4 fils - 20 A",
        fils16:"4 fils - 30 A",
        fils17:"4 fils - 50 A",
        fils18:"4 fils - 63 A",
        fils19:"4 fils - 75 A",
        fils20:"4 fils - 80 A",
        fils21:"4 fils - 100 A",
        fils22:"4 fils - 125 A",
        fils23:"4 fils - 160 A",
        fils24:"4 fils - 200 A",
        fils25:"4 fils - 250 A",
        fils26:"4 fils - 300 A",
        consomation:"Consommation",
        compteurGaz:"Compteur gaz",
        puisDebit:"Puissance/Débit",
        btSimuler:"Simuler",
        domestic:"Domestique",
        nndomestic:"Non domestique",    
        compteurEclai:"Compteur éclairage",
        placeholderSim:"Tapez ici votre consommation",
        placeholderCons:"Rédigez votre réclamation ici",
        simfacFactSim:"Facture simulé",
        simfacNnmois:"Nombre de mois",
        simdacConselect:"Consommation électrique",
        simdacCongaz:"Consommation gaz",
        simfacmontantgaz:"Montant gaz",
        simfactmontantTotal:"Montant totale",
        quitter:"Quitter",
        typerec:"Type de la réclamation:",
        typerec1:"Réclamation et renseignants sur facture:",
        typerec2:"Relance pour étude ou exécution",
        typerec3:"Réclamation pour réfection trottoir",
        typerec4:"Réclamation pour constats dégéts matériels suite incident",
        typerec5:"Vérification de tension ou pression",
        typerec6:"Vérification de disjoncter  ou détenteur ou compteur",
        typerec7:"Correction dadress ou nom",
        typerec8:"Autre",
        daterec:"Date:",
        recETitle:"Type de réclamation:",
        recEReponse:"Réponse:",
        recERoFact:"Aucune facture trouvé",
        factueSMontant:"Montant:",
        affichfactDatDeb:"Date Debut:",
        affichfactDatFin:"Date Fin:",
        affichfactEtat:"Etat:",
        affichfactInterdit:"Interdit!",
        affichfactAlert:"S'il vous plais ajouter une référence d'abord",
        affichfactOk:"OK",
        affichfactAnnuler:"Annuler",
        demandeType:"Type de la demande:",
        demandLabel1:"Nouveau Branchement",
        demandLabel2:"Remplacer ou Deplacer Compteur",
        demandePlaceholder:"Rédigez Votre Demande ici",
        refPlacholder:"Tapez ici Référence",
        refPlacholder1:"Tapez ici  Le code dessus",
        refbtn_add:"Ajouter",
        fsFactSim:"Facture simulé",
        fsMonTtal:"Montant electrique:",
        histDemanEnv:"Demandes envoyées",
        histRecEnv:"Réclamations envoyées",
        histFactSim:"Factures simulées",
        payerfactTitle:"Vous trouvez ici le resumé du votre facture:",
        payerfactact:"Facture",
        payerfactPayer:"Payer",
        recMessageRec:"Message de réclamation:",
        affFact:"Tapez une date ici...",
        dsMEssageDem:"Message de la demande:",
        helpf1n:"Numero de Service",
        helpf2n:"Numero Vert",
        bienvenue:"Bienvenue",
        custFact:"Facturation:",
        custFact1:"Factures",
        custSim:"Simulation",
        custDeco:"Déconnexion",
        custNote:"Noter les services",
        custMap:"Map",
        custSite:"Site offciel STEG",
        custHelp:"Aide",
        custAcc:"Accueil",
langueARb:"Langue arabe",
langueFR:"Langue Francaise",
langueEn:"Langue Englais",
parlng:"Choisissez la langue de votre application:",





    },
    fr:{
        parametre:"Paramétres",
        votre_ref:"Votre référence",
        votre_profil:"Profile",
        chnage_ref:"Changer la référence",
        add_ref:"Pour continuer ajouter une référence",
        factur:"Facturation",
        hist:"Historique",
        demande:"Demande",
        rec:"Réclamation",
        bt_env:"Envoyer",
        datedeb:"Date de Debut",
        period_cons:"Période de Consommation:",
        usage:"Usage",
        moisWehed:"1 mois",
        moisWehed2:"2 mois",
        moisWehed4:"4 mois",
        moisWehed6:"6 mois",
        moisWehed8:"8 mois",
        moisWehed10:"10 mois",
        moisWehed12:"12 mois",
        fils:"2 fils - 5 A",
        fils1:"2 fils - 10 A",
        fils2:"2 fils - 5 A",
        fils3:"2 fils - 15 A",
        fils4:"2 fils - 20 A",
        fils5:"2 fils - 30 A",
        fils6:"2 fils - 45 A",
        fils7:"2 fils - 63 A",
        fils8:"2 fils - 100 A",
        fils9:"2 fils - 125 A",
        fils10:"2 fils - 160 A",
        fils11:"2 fils - 225 A",
        fils12:"4 fils - 5 A",
        fils13:"4 fils - 10 A",
        fils14:"4 fils - 15 A",
        fils15:"4 fils - 20 A",
        fils16:"4 fils - 30 A",
        fils17:"4 fils - 50 A",
        fils18:"4 fils - 63 A",
        fils19:"4 fils - 75 A",
        fils20:"4 fils - 80 A",
        fils21:"4 fils - 100 A",
        fils22:"4 fils - 125 A",
        fils23:"4 fils - 160 A",
        fils24:"4 fils - 200 A",
        fils25:"4 fils - 250 A",
        fils26:"4 fils - 300 A",
        consomation:"Consommation",
        compteurGaz:"Compteur gaz",
        puisDebit:"Puissance/Débit",
        btSimuler:"Simuler",
        domestic:"Domestique",
        nndomestic:"Non domestique",    
        compteurEclai:"Compteur éclairage",
        placeholderSim:"Tapez ici votre consommation",
        placeholderCons:"Rédigez votre réclamation ici",
        simfacFactSim:"Facture simulé",
        simfacNnmois:"Nombre de mois",
        simdacConselect:"Consommation électrique",
        simdacCongaz:"Consommation gaz",
        simfacmontantgaz:"Montant gaz",
        simfactmontantTotal:"Montant totale",
        quitter:"Quitter",
        typerec:"Type de la réclamation:",
        typerec1:"Réclamation et renseignants sur facture:",
        typerec2:"Relance pour étude ou exécution",
        typerec3:"Réclamation pour réfection trottoir",
        typerec4:"Réclamation pour constats dégéts matériels suite incident",
        typerec5:"Vérification de tension ou pression",
        typerec6:"Vérification de disjoncter  ou détenteur ou compteur",
        typerec7:"Correction dadress ou nom",
        typerec8:"Autre",
        daterec:"Date:",
        recETitle:"Type de réclamation:",
        recEReponse:"Réponse:",
        recERoFact:"Aucune facture trouvé",
        factueSMontant:"Montant:",
        affichfactDatDeb:"Date Debut:",
        affichfactDatFin:"Date Fin:",
        affichfactEtat:"Etat:",
        affichfactInterdit:"Interdit!",
        affichfactAlert:"S'il vous plais ajouter une référence d'abord",
        affichfactOk:"OK",
        affichfactAnnuler:"Annuler",
        demandeType:"Type de la demande:",
        demandLabel1:"Nouveau Branchement",
        demandLabel2:"Remplacer ou Deplacer Compteur",
        demandePlaceholder:"Rédigez Votre Demande ici",
        refPlacholder:"Tapez ici Référence",
        refPlacholder1:"Tapez ici  Le code dessus",
        refbtn_add:"Ajouter",
        fsFactSim:"Facture simulé",
        fsMonTtal:"Montant electrique:",
        histDemanEnv:"Demandes envoyées",
        histRecEnv:"Réclamations envoyées",
        histFactSim:"Factures simulées",
        payerfactTitle:"Vous trouvez ici le resumé du votre facture:",
        payerfactact:"Facture",
        payerfactPayer:"Payer",
        recMessageRec:"Message de réclamation:",
        affFact:"Tapez une date ici...",
        dsMEssageDem:"Message de la demande:",
        helpf1n:"Numero de Service",
        helpf2n:"Numero Vert",
        bienvenue:"Bienvenue",
        custFact:"Facturation:",
        custFact1:"Factures",
        custSim:"Simulation",
        custDeco:"Déconnexion",
        custNote:"Noter les services",
        custMap:"Map",
        custSite:"Site offciel STEG",
        custHelp:"Aide",
        custAcc:"Accueil",
        langueARb:"Langue arabe",
        langueFR:"Langue Francaise",
        langueEn:"Langue Englais",
        parlng:"Choisissez la langue de votre application:",
        


    },
    en: {     
        parametre:"Settings",
        votre_ref:"Your reference",
        votre_profil:"Profile",
        chnage_ref:"Change the reference",
        add_ref:"To continue add a reference",
        factur:"Billing",
        hist:"Historical",
        demande:"Request",
        rec:"Claim",
        bt_env:"Send",
        datedeb:"Start date:",
        period_cons:"Consumption Period",
        usage:"Use",
        moisWehed:"1 month",
        moisWehed2:"2 month",
        moisWehed4:"4 month",
        moisWehed6:"6 month",
        moisWehed8:"8 month",
        moisWehed10:"10 month",
        moisWehed12:"12 month",
        fils:"2 wires - 5 A",
        fils1:"2 wires - 10 A",
        fils2:"2 wires - 5 A",
        fils3:"2 wires - 15 A",
        fils4:"2 wires - 20 A",
        fils5:"2 wires - 30 A",
        fils6:"2 wires - 45 A",
        fils7:"2 wires - 63 A",
        fils8:"2 wires - 100 A",
        fils9:"2 wires - 125 A",
        fils10:"2 wires - 160 A",
        fils11:"2 wires - 225 A",
        fils12:"4 wires - 5 A",
        fils13:"4 wires - 10 A",
        fils14:"4 wires - 15 A",
        fils15:"4 wires - 20 A",
        fils16:"4 wires - 30 A",
        fils17:"4 wires - 50 A",
        fils18:"4 wires - 63 A",
        fils19:"4 wires - 75 A",
        fils20:"4 wires - 80 A",
        fils21:"4 wires - 100 A",
        fils22:"4 wires - 125 A",
        fils23:"4 wires - 160 A",
        fils24:"4 wires - 200 A",
        fils25:"4 wires - 250 A",
        fils26:"4 wires - 300 A",
        consomation:"Consumption",
        compteurGaz:"Gas meter",
        puisDebit:"Power / Flow",
        btSimuler:"Simulate",
        domestic:"Local",
        nndomestic:"not domestic",    
        compteurEclai:"Lighting counter",
        placeholderSim:"Type your consumption here",
       placeholderCons:"Write your complaint here",
       simfacFactSim:"Simulated invoice",
       simfacNnmois:"Number of months",
       simdacConselect:"Power consumption",
       simdacCongaz:"Gas consumption",
       simfacmontantgaz:"Gas amount",
       simfactmontantTotal:"Total amount",
       quitter:"leave",
       typerec:"Type of complaint:",
       typerec1:"Complaint and information on invoice",
       typerec2:"Recovery for study or execution",
       typerec3:"Sidewalk Reclamation Claim",
       typerec4:"Complaint for damage to property following incident",
       typerec5:"Voltage or pressure check",
       typerec6:"Circuit breaker or holder or counter verification",
       typerec7:"Address or name correction",
       typerec8:"Other",
       daterec:"Dated:",
       recETitle:"Type of complaint:",
       recEReponse:"Reply:",
       recERoFact:"No invoice found",
       factueSMontant:"Amount:",
       affichfactDatDeb:"Start date:",
       affichfactDatFin:"End date:",
       affichfactEtat:"State:",
       affichfactInterdit:"Not allowed!",
       affichfactAlert:"Please add a reference first",
       affichfactOk:"okay",
       affichfactAnnuler:"Cancel",  
       demandeType:"Request type:",
        demandLabel1:"New contact",
        demandLabel2:"Replace or move the counter",
        demandePlaceholder:"Type your request here",
       refPlacholder:"Type Reference here",
       refPlacholder1:"Type the code here",
       refbtn_add:"Add",
       fsFactSim:"Simulated invoice",
       fsMonTtal:"Electric upright:",
       histDemanEnv:"Complaints sent",
       histRecEnv:"Requests sent",
       histFactSim:"Simulated invoices",
       payerfactTitle:"Here you find the summary of your invoice:",
       payerfactact:"Bill",
       payfactPayer: "Pay",
       recMessageRec: "Complaint message:",
       affFact: "Type a date here ...",
       dsMEssageDem: "Request message:",
       helpf1n: "Service Number",
       helpf2n: "Green Number",
       bienvenue:"Welcome",
       custFact: "Billing:",
        custFact1: "Invoices",
        custSim: "Simulation",
        custDeco: "Logout",
        custNote: "Rate services",
         custMap: "Map",
         custSite: "STEG official website",
         custHelp: "Help",
         custAcc: "Home",
         langueARb:"Arabic language",
         langueFR:"French language",
         langueEn:"Langue Anglais",
         parlng:"Choose the language of your application:",


    },
    ar:{
     parametre:"الإعدادات ",
     votre_ref:"المرجعية الخاصة بك:",
     votre_profil:"الملف الشخصي",
     chnage_ref:"قم بتغيير المرجع",
     add_ref:"لمواصلة إضافة مرجع",
     factur:"الفواتير",
     hist:"تاريخي",
     demande:"طلب",
     rec:"شكوى",
     bt_env:"إرسال",
     datedeb:"تاريخ البداية:",
     period_cons:"فترة الاستهلاك",
     usage:"استخدام",
     moisWehed:"شهر 1",
     moisWehed2:"شهر 2",
     moisWehed4:"شهر 4",
     moisWehed6:"شهر 6",
     moisWehed8:"شهر 8",
     moisWehed10:"شهر 10",
     moisWehed12:"شهر 12",
     fils:"2 سلك - 5 أ",
     fils1:"2 سلك - 10 أ",
     fils2:"2 سلك - 5 أ",
     fils3:"2 سلك - 15 أ",
     fils4:"2 سلك - 20 أ",
     fils5:"2 سلك - 20 أ",
     fils6:"2 سلك - 45 أ",
     fils7:"2 سلك - 63 أ",
     fils8:"2 سلك - 100 أ",
     fils9:"2 سلك - 125 أ",
     fils10:"2 سلك - 160 أ",
     fils11:"2 سلك - 225 أ",
     fils12:"4 أسلاك - 5 أ",
     fils13:"4 أسلاك - 10 أ",
     fils14:"4 أسلاك - 15 أ",
     fils15:"4 أسلاك - 20 أ",
     fils16:"4 أسلاك - 30 أ",
     fils17:"4 أسلاك - 50 أ",
     fils18:"4 أسلاك - 63 أ",
     fils19:"4 أسلاك - 63 أ",
     fils20:"4 أسلاك - 80 أ",
     fils21:"4 أسلاك - 100 أ",
     fils22:"4 أسلاك - 125 أ",
     fils23:"4 أسلاك - 160 أ",
     fils24:"4 أسلاك - 200 أ",
     fils25:"4 أسلاك - 250 أ",
     fils26:"4 أسلاك - 300 أ",
    consomation:"استهلاك",
    compteurGaz:"متر غاز",
    puisDebit:"تدفق الطاقة",
    btSimuler:"محاكاة",
    domestic:"محلي",
    nndomestic:"غير محلي",    
    compteurEclai:"عداد إضاءة",
    placeholderSim:"اكتب استهلاكك هنا",
    placeholderCons:"اكتب شكواك هنا",
    quitter:"خروج",
    typerec:"نوع الشكوى:",
    typerec1:"شكوى ومعلومات عن الفاتورة",
    typerec2:"الانتعاش للدراسة أو التنفيذ",
    typerec3:"المطالبة باستعادة الرصيف",
    typerec4:"شكوى عن الأضرار التي لحقت بالممتلكات بعد الحادث",
    typerec5:"فحص الجهد أو الضغط",
    typerec6:"قاطع الدائرة أو حامل أو التحقق من العداد",
    typerec7:"تصحيح العنوان أو الاسم",   
    typerec8:"آخر",
    daterec:"بتاريخ:",
    recETitle:"نوع الشكوى:",
    recERoFact:"لم يتم العثور على فاتورة",
    factueSMontant:"كمية:",
    affichfactDatDeb:"تاريخ البداية:",
    affichfactDatFin:"تاريخ النهاية:",
    affichfactEtat:"حالة:",
    affichfactInterdit:"غير مسموح!",
    affichfactAlert:"يرجى إضافة مرجع أولاً",
    affichfactOk:"حسنا",
    affichfactAnnuler:"الغاء",
    demandeType:"نوع الطلب:",
    demandLabel1:"اتصال جديد",
    demandLabel2:"استبدال أو تحريك العداد",
    demandePlaceholder:"اكتب طلبك هنا",
    refPlacholder:"اكتب المرجع هنا",
    refPlacholder1:"اكتب الرمز هنا",
    refbtn_add:"إضافة",
    fsFactSim:"فاتورة محاكاة",
    fsMonTtal:"تستقيم الكهربائية:",
    histDemanEnv:"الطلبات المرسلة",
    histRecEnv:"الشكوى المرسلة",
    histFactSim:"فواتير محاكاة",
    payerfactTitle:"ستجد هنا ملخص فاتورتك:",
    payfactPayer: "ادفع",
    recMessageRec: "رسالة شكوى:",
    affFact: "اكتب تاريخًا هنا ...",
    dsMEssageDem: "طلب رسالة:" ,
    helpf1n: "رقم الخدمة" ,
    helpf2n: "الرقم الأخضر" ,
    bienvenue:"مرحباً ",
    custFact: "الفوترة:" ,
    custFact1: "الفواتير" ,
    custSim: "المحاكاة" ,
    custDeco: "تسجيل الخروج" ,
    custNote: "تقييم الخدمات" ,
         custMap: "الخريطة" ,
         custSite: "موقع STEG الرسمي" ,
         custHelp: "مساعدة" ,
         custAcc: "المنزل" ,
         langueARb:"اللغة العربية",
         langueFR:"اللغة الفرنسية",
         langueEn:"اللغة الانجليزية ",
         parlng:"اختر لغة تطبيقك:",





    }
   });

